#!/usr/bin/env bash

cd "$(dirname "$0")"
ROOT=$(pwd)

set -e

print_success_message () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

make_symbolic_link() {
  ln -sfn $1 $2
  print_success_message "Linked $1 to $2"
}

install() {
  source=$1
  dest=$2
  if ! [ -d "$source" -o -d "$dest" ]; then
    echo "Source and destiniation parameters must be valid direcotries."
  fi

  echo "S: $source, D: $dest"
  for file in `find "$source"`
  do
    if [ "$file" = "$source" ]; then
      continue
    fi
    dest_loc="$dest/`basename $file`"
    source_loc="$ROOT/$file"
    make_symbolic_link $source_loc $dest_loc
  done
}

install "dotfiles" "$HOME"
make_symbolic_link "$(pwd)/jakobbossek.zsh-theme" "$HOME/.oh-my-zsh/themes/"
